# Generated by Django 4.1.2 on 2022-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('INST', 'Instaram'), ('VK', 'Vkontakte'), ('FCBK', 'Facebook')], max_length=10)),
                ('img', models.ImageField(height_field=100, upload_to='pattern', width_field=100)),
            ],
        ),
    ]
