# Generated by Django 4.1.2 on 2022-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='img',
            field=models.ImageField(height_field=2000, upload_to='pattern', width_field=2000),
        ),
    ]
